# Generated by Django 6.0.4 on 2026-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(default='80038233', max_length=12, unique=True)),
                ('original_request', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('entities', models.JSONField(default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('assigned_team', models.CharField(max_length=50)),
                ('process_steps', models.JSONField(default=list)),
                ('whatsapp_message', models.TextField()),
                ('email_message', models.TextField()),
                ('sms_message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
